// Copyright (c) 2026 DSH ESP32 dial project.
// SPDX-License-Identifier: MIT
//
// LVGL round-dial UI implementation. See DialUi.h for the layout rationale.

#include "DialUi.h"

#include <string.h>

#include "Config.h"

// Custom CJK font generated by tools/build-font.ps1. Contains exactly the
// Chinese characters this firmware renders, plus the ASCII range — no boxes.
LV_FONT_DECLARE(dsh_font_cjk_16);

// DeepSeek whale icon — a small 16×16 image shown on the idle screen.
#include "WhaleIcon.h"

// The QR widget comes from LVGL's extras, which `lvgl.h` already includes; it
// exists only when lv_conf.h sets LV_USE_QRCODE, so fail loudly at compile time
// rather than at runtime on a dial that cannot show its own setup code.
#if LV_USE_QRCODE == 0
#error "LV_USE_QRCODE must be 1 in lv_conf.h for the provisioning screen"
#endif

// ── LVGL colours ─────────────────────────────────────────────────────────
// DeepSeek brand blue, plus clean signal colours for the five phases.
static constexpr lv_color_t kBlue = LV_COLOR_MAKE(0x1E, 0x88, 0xE5);
static constexpr lv_color_t kDarkBg = LV_COLOR_MAKE(0x0D, 0x11, 0x1D);
static constexpr lv_color_t kGreen = LV_COLOR_MAKE(0x4C, 0xAF, 0x50);
static constexpr lv_color_t kRed = LV_COLOR_MAKE(0xE5, 0x39, 0x35);
static constexpr lv_color_t kYellow = LV_COLOR_MAKE(0xFF, 0xCC, 0x00);
static constexpr lv_color_t kGray = LV_COLOR_MAKE(0x55, 0x55, 0x55);
static constexpr lv_color_t kWhite = LV_COLOR_MAKE(0xFF, 0xFF, 0xFF);
static constexpr lv_color_t kDim = LV_COLOR_MAKE(0x22, 0x22, 0x33);
static constexpr lv_color_t kPurple = LV_COLOR_MAKE(0x7C, 0x4D, 0xFF);  // thinking phase

// ── static members ───────────────────────────────────────────────────────
lv_style_t DialUi::mainStyle_;
bool DialUi::stylesInitialised_ = false;
DialUi dialUi;  // global instance

// Arc progress animation: one reusable descriptor + exec callback. File scope
// so updateArc can stop/resume without the class header exposing LVGL internals.
static lv_anim_t arcAnim_;
static void arcAnimCb_(void* obj, int32_t v) {
  lv_arc_set_value(static_cast<lv_obj_t*>(obj), static_cast<int16_t>(v));
}

// ── colour mapping ───────────────────────────────────────────────────────
lv_color_t DialUi::colorForPhase(DialPhase phase, bool stale) {
  if (stale) return kGray;
  switch (phase) {
    case DialPhase::Idle:      return kDim;
    case DialPhase::Working:   return kBlue;
    case DialPhase::Thinking:  return kPurple;
    case DialPhase::Waiting:   return kYellow;
    case DialPhase::Done:      return kGreen;
    case DialPhase::Error:     return kRed;
    case DialPhase::Offline:   return kGray;
  }
  return kGray;
}

// ── constructor & initialisation ─────────────────────────────────────────

DialUi::DialUi() {}

void DialUi::begin() {
  if (!stylesInitialised_) {
    lv_style_init(&mainStyle_);
    lv_style_set_bg_color(&mainStyle_, kDarkBg);
    lv_style_set_text_color(&mainStyle_, kWhite);
    lv_style_set_radius(&mainStyle_, 180);  // round clip
    stylesInitialised_ = true;
  }

  lv_obj_add_style(lv_scr_act(), &mainStyle_, 0);
  lv_obj_set_style_bg_color(lv_scr_act(), kDarkBg, 0);
  lv_obj_set_style_radius(lv_scr_act(), 180, 0);  // clip to circle

  buildMainScreen();
  buildAskOverlay();
  buildProvisioningScreen();

  // Start in the offline state: nothing has been heard from the bridge yet, and
  // the dial must never imply otherwise.
  setPhaseLabel(DialPhase::Offline);
  lv_obj_set_style_bg_color(statusBg_, colorForPhase(DialPhase::Offline, false), 0);
  lv_label_set_text(titleLabel_, "DSH");
  lv_label_set_text(detailLabel_, "connecting...");
  updateArc(0);
}

// ── main screen layout ───────────────────────────────────────────────────

void DialUi::buildMainScreen() {
  lv_obj_t* scr = lv_scr_act();

  // Background circle — fills the 360×360 area so the phase colour is visible.
  statusBg_ = lv_obj_create(scr);
  lv_obj_set_size(statusBg_, 360, 360);
  lv_obj_set_pos(statusBg_, 0, 0);
  lv_obj_set_style_radius(statusBg_, 180, 0);
  lv_obj_set_style_border_width(statusBg_, 0, 0);
  lv_obj_set_style_bg_color(statusBg_, kDim, 0);
  lv_obj_set_style_bg_opa(statusBg_, 255, 0);

  // A long press anywhere on the dial re-opens provisioning, so a change of
  // network never forces a cable. The arc above swallows its own presses, so
  // the gesture has to live on the full-screen background.
  lv_obj_add_event_cb(statusBg_, DialUi::backgroundLongPressed,
                      LV_EVENT_LONG_PRESSED, nullptr);

  // Context pressure arc → outer ring, indicator mode.
  // LVGL's 0° is at 3 o'clock (right), so the arc initially grows from the
  // right side — every state change the indicator bar starts at 3 o'clock,
  // which looks like "每次的位置都不一样". Fix: shift the arc's working
  // range to 270°–630° (12 o'clock, top of the dial), so 0% context pressure
  // sits at the top and the indicator grows clockwise from there.
  arc_ = lv_arc_create(scr);
  lv_obj_set_size(arc_, 340, 340);
  lv_obj_set_pos(arc_, 10, 10);
  lv_arc_set_mode(arc_, LV_ARC_MODE_NORMAL);
  lv_arc_set_range(arc_, 0, 100);
  lv_arc_set_value(arc_, 0);
  // The end angle must be written as 269, not 630. LVGL normalises anything
  // above 360 (`while (end > 360) end -= 360`), so 630 lands back on 270 and the
  // background span collapses to zero width. value_update() then maps the
  // percentage onto that empty span — lv_map(v, 0, 100, 270, 270) is always 270
  // — and the indicator sits frozen at its origin no matter what arrives.
  //
  // An end angle *below* the start is the documented way to express a wrap: LVGL
  // adds 360 internally (`if (bg_angle_end < bg_angle_start) bg_end += 360`), so
  // 270 → 269 becomes a 359° sweep clockwise from 12 o'clock, which is the full
  // ring we want with a 1° seam at the top.
  lv_arc_set_bg_angles(arc_, 270, 269);
  lv_arc_set_angles(arc_, 270, 270);  // empty indicator; set_value drives it
  lv_obj_set_style_arc_width(arc_, 8, 0);
  lv_obj_set_style_arc_color(arc_, kGray, LV_PART_INDICATOR);
  lv_obj_set_style_arc_opa(arc_, 80, LV_PART_INDICATOR);
  lv_obj_set_style_arc_color(arc_, kDim, LV_PART_MAIN);
  lv_obj_set_style_arc_opa(arc_, 30, LV_PART_MAIN);
  lv_obj_clear_flag(arc_, LV_OBJ_FLAG_CLICKABLE);

  // Phase icon — deliberately small. A 48px glyph filled the circle and left no
  // room for the information a status dial exists to show; at 20px it reads as
  // an indicator beside the title instead of competing with it.
  phaseLabel_ = lv_label_create(scr);
  lv_obj_align(phaseLabel_, LV_ALIGN_TOP_MID, 0, 62);
  lv_obj_set_style_text_font(phaseLabel_, &lv_font_montserrat_20, 0);
  lv_obj_set_style_text_color(phaseLabel_, kWhite, 0);
  lv_label_set_text(phaseLabel_, LV_SYMBOL_MINUS);

  // Small DeepSeek whale icon, top-right of the title area.
  // Uses a simple LVGL image in raw format (no external converter needed).
  // The pixel data is defined in WhaleIcon.cpp as RGB565 with chroma key.
  whaleIcon_ = lv_img_create(scr);
  lv_img_set_src(whaleIcon_, &whaleIcon);
  lv_obj_align(whaleIcon_, LV_ALIGN_TOP_RIGHT, -8, 60);

  // Title — session title, under the icon.
  titleLabel_ = lv_label_create(scr);
  lv_obj_align(titleLabel_, LV_ALIGN_TOP_MID, 0, 88);
  lv_obj_set_style_text_font(titleLabel_, &dsh_font_cjk_16, 0);
  lv_obj_set_style_text_color(titleLabel_, kWhite, 0);
  lv_label_set_long_mode(titleLabel_, LV_LABEL_LONG_SCROLL_CIRCULAR);
  lv_obj_set_width(titleLabel_, 250);
  lv_obj_set_style_text_align(titleLabel_, LV_TEXT_ALIGN_CENTER, 0);
  lv_label_set_text(titleLabel_, "");

  // ── idle face ──────────────────────────────────────────────────────────
  // A desk device that is not working should still be worth looking at, so the
  // idle phase is a clock. The clock sits at 32px (not 48) so the three-column
  // stat grid on either side has room to breathe — matching the HTML mockup.
  clockLabel_ = lv_label_create(scr);
  lv_obj_align(clockLabel_, LV_ALIGN_CENTER, 0, -24);
  lv_obj_set_style_text_font(clockLabel_, &lv_font_montserrat_32, 0);
  lv_obj_set_style_text_color(clockLabel_, kWhite, 0);
  lv_label_set_text(clockLabel_, "--:--");
  lv_obj_add_flag(clockLabel_, LV_OBJ_FLAG_HIDDEN);

  clockSubLabel_ = lv_label_create(scr);
  lv_obj_align(clockSubLabel_, LV_ALIGN_CENTER, 0, 8);
  lv_obj_set_style_text_font(clockSubLabel_, &dsh_font_cjk_16, 0);
  lv_obj_set_style_text_color(clockSubLabel_, kGray, 0);
  lv_label_set_text(clockSubLabel_, "空闲中");
  lv_obj_add_flag(clockSubLabel_, LV_OBJ_FLAG_HIDDEN);

  // ── idle three-column stats ────────────────────────────────────────────
  // Four rows per side. Value labels (white) and name labels (gray) are
  // separate objects so no recolor parsing is needed — each label has exactly
  // one colour. Everything sits inside the round screen's inner zone (the arc
  // ring occupies radius 162..170, so content must stay within ~160 of the
  // centre). Left column x=22..128 right-aligned, right column 232..338
  // left-aligned, clock column between them — mirroring the HTML v6.1 grid.
  const lv_coord_t rowY[] = { 130, 166, 202, 238 };

  for (int i = 0; i < 4; ++i) {
    idleColLeft_[i] = lv_label_create(scr);
    lv_obj_set_pos(idleColLeft_[i], 22, rowY[i]);
    lv_obj_set_width(idleColLeft_[i], 106);
    lv_obj_set_style_text_font(idleColLeft_[i], &dsh_font_cjk_16, 0);
    lv_obj_set_style_text_color(idleColLeft_[i], kWhite, 0);
    lv_label_set_long_mode(idleColLeft_[i], LV_LABEL_LONG_DOT);
    lv_obj_set_style_text_align(idleColLeft_[i], LV_TEXT_ALIGN_LEFT, 0);
    lv_label_set_text(idleColLeft_[i], "");
    lv_obj_add_flag(idleColLeft_[i], LV_OBJ_FLAG_HIDDEN);

    idleColRight_[i] = lv_label_create(scr);
    lv_obj_set_pos(idleColRight_[i], 232, rowY[i]);
    lv_obj_set_width(idleColRight_[i], 106);
    lv_obj_set_style_text_font(idleColRight_[i], &dsh_font_cjk_16, 0);
    lv_obj_set_style_text_color(idleColRight_[i], kWhite, 0);
    lv_label_set_long_mode(idleColRight_[i], LV_LABEL_LONG_DOT);
    lv_obj_set_style_text_align(idleColRight_[i], LV_TEXT_ALIGN_RIGHT, 0);
    lv_label_set_text(idleColRight_[i], "");
    lv_obj_add_flag(idleColRight_[i], LV_OBJ_FLAG_HIDDEN);
  }

  // ── idle stat name labels ─────────────────────────────────────────────
  // Per-row names sit just above their value, in gray. Fixed at build time —
  // setState only fills the value labels.
  for (int i = 0; i < 4; ++i) {
    const char* leftNames[] = { "轮次", "步数", "LLM", "工具" };
    idleNameLeft_[i] = lv_label_create(scr);
    lv_obj_set_pos(idleNameLeft_[i], 22, rowY[i] - 18);
    lv_obj_set_width(idleNameLeft_[i], 106);
    lv_obj_set_style_text_font(idleNameLeft_[i], &dsh_font_cjk_16, 0);
    lv_obj_set_style_text_color(idleNameLeft_[i], kGray, 0);
    lv_label_set_long_mode(idleNameLeft_[i], LV_LABEL_LONG_DOT);
    lv_obj_set_style_text_align(idleNameLeft_[i], LV_TEXT_ALIGN_LEFT, 0);
    lv_label_set_text(idleNameLeft_[i], leftNames[i]);
    lv_obj_add_flag(idleNameLeft_[i], LV_OBJ_FLAG_HIDDEN);

    const char* rightNames[] = { "首token", "速度", "缓存", "输入" };
    idleNameRight_[i] = lv_label_create(scr);
    lv_obj_set_pos(idleNameRight_[i], 232, rowY[i] - 18);
    lv_obj_set_width(idleNameRight_[i], 106);
    lv_obj_set_style_text_font(idleNameRight_[i], &dsh_font_cjk_16, 0);
    lv_obj_set_style_text_color(idleNameRight_[i], kGray, 0);
    lv_label_set_long_mode(idleNameRight_[i], LV_LABEL_LONG_DOT);
    lv_obj_set_style_text_align(idleNameRight_[i], LV_TEXT_ALIGN_RIGHT, 0);
    lv_label_set_text(idleNameRight_[i], rightNames[i]);
    lv_obj_add_flag(idleNameRight_[i], LV_OBJ_FLAG_HIDDEN);
  }

  // ── working face: the tool-call activity list ───────────────────────────
  // Three rows, stacked centre-out. The running row is opaque and the finished
  // ones fade, so the eye lands on what is happening now without reading.
  for (uint8_t i = 0; i < kActivityLines; ++i) {
    activityRows_[i] = lv_label_create(scr);
    lv_obj_align(activityRows_[i], LV_ALIGN_CENTER, 0,
                 static_cast<lv_coord_t>(-16 + i * 24));
    lv_obj_set_style_text_font(activityRows_[i], &dsh_font_cjk_16, 0);
    lv_obj_set_style_text_color(activityRows_[i], kWhite, 0);
    lv_obj_set_style_text_align(activityRows_[i], LV_TEXT_ALIGN_CENTER, 0);
    lv_label_set_long_mode(activityRows_[i], LV_LABEL_LONG_DOT);
    lv_obj_set_width(activityRows_[i], 250);
    lv_label_set_text(activityRows_[i], "");
    lv_obj_add_flag(activityRows_[i], LV_OBJ_FLAG_HIDDEN);
  }

  // Detail — one line naming the current action, below the activity list.
  detailLabel_ = lv_label_create(scr);
  lv_obj_align(detailLabel_, LV_ALIGN_CENTER, 0, 62);
  lv_obj_set_style_text_font(detailLabel_, &dsh_font_cjk_16, 0);
  lv_obj_set_style_text_color(detailLabel_, kGray, 0);
  lv_label_set_long_mode(detailLabel_, LV_LABEL_LONG_SCROLL_CIRCULAR);
  lv_obj_set_width(detailLabel_, 250);
  lv_obj_set_style_text_align(detailLabel_, LV_TEXT_ALIGN_CENTER, 0);
  lv_label_set_text(detailLabel_, "");

  // ── idle statistics ticker ──────────────────────────────────────────────
  // ── always-on footer ────────────────────────────────────────────────────
  // Link state and battery stay visible in every phase: when the dial says
  // nothing is happening, the footer is what proves it still knows.
  //
  // The icon and text MUST be separate labels. LVGL's built-in symbols live in
  // the Montserrat font range (0xF1xx), but the CJK font has no symbol glyphs —
  // rendering LV_SYMBOL_WIFI with SIMSUN would draw a box. Chinese text, in
  // turn, is absent from Montserrat. So the footer is two labels side by side,
  // each with the font that contains its content. Verified against the SIMSUN
  // CJK character list: it holds only ~1000 Han radicals plus basic ASCII, no
  // punctuation, no symbols, no mid-dots (·), no box-drawing (│).
  footerIcon_ = lv_label_create(scr);
  lv_obj_align(footerIcon_, LV_ALIGN_BOTTOM_MID, -70, -40);
  lv_obj_set_style_text_font(footerIcon_, &lv_font_montserrat_20, 0);
  lv_obj_set_style_text_color(footerIcon_, kGray, 0);
  lv_label_set_text(footerIcon_, "");

  footerText_ = lv_label_create(scr);
  lv_obj_align(footerText_, LV_ALIGN_BOTTOM_MID, -36, -40);
  lv_obj_set_style_text_font(footerText_, &dsh_font_cjk_16, 0);
  lv_obj_set_style_text_color(footerText_, kGray, 0);
  lv_label_set_text(footerText_, "");

  footerRight_ = lv_label_create(scr);
  lv_obj_align(footerRight_, LV_ALIGN_BOTTOM_MID, 52, -40);
  lv_obj_set_style_text_font(footerRight_, &dsh_font_cjk_16, 0);
  lv_obj_set_style_text_color(footerRight_, kGray, 0);
  lv_label_set_text(footerRight_, "");

  // Context pressure text under the clock — the arc already shows it as a ring,
  // but the number belongs next to the idle readout, not competing for footer
  // width. Shown only while idle; setState fills it.
  footerMid_ = lv_label_create(scr);
  lv_obj_align(footerMid_, LV_ALIGN_CENTER, 0, 34);
  lv_obj_set_style_text_font(footerMid_, &dsh_font_cjk_16, 0);
  lv_obj_set_style_text_color(footerMid_, kGray, 0);
  lv_label_set_text(footerMid_, "");
  lv_obj_add_flag(footerMid_, LV_OBJ_FLAG_HIDDEN);
}

// ── ask overlay ──────────────────────────────────────────────────────────

void DialUi::buildAskOverlay() {
  askBg_ = lv_obj_create(lv_scr_act());
  lv_obj_set_size(askBg_, 360, 360);
  lv_obj_set_pos(askBg_, 0, 0);
  lv_obj_set_style_radius(askBg_, 180, 0);
  lv_obj_set_style_border_width(askBg_, 0, 0);
  lv_obj_set_style_bg_color(askBg_, kYellow, 0);
  lv_obj_set_style_bg_opa(askBg_, 255, 0);
  lv_obj_add_flag(askBg_, LV_OBJ_FLAG_HIDDEN);

  askTitle_ = lv_label_create(askBg_);
  lv_obj_align(askTitle_, LV_ALIGN_TOP_MID, 0, 28);
  lv_obj_set_style_text_font(askTitle_, &dsh_font_cjk_16, 0);
  lv_obj_set_style_text_color(askTitle_, kDarkBg, 0);
  lv_label_set_long_mode(askTitle_, LV_LABEL_LONG_WRAP);
  lv_obj_set_width(askTitle_, 280);
  lv_label_set_text(askTitle_, "");

  askBody_ = lv_label_create(askBg_);
  lv_obj_align(askBody_, LV_ALIGN_TOP_MID, 0, 68);
  lv_obj_set_style_text_font(askBody_, &dsh_font_cjk_16, 0);
  lv_obj_set_style_text_color(askBody_, LV_COLOR_MAKE(0x33, 0x33, 0x33), 0);
  lv_label_set_long_mode(askBody_, LV_LABEL_LONG_WRAP);
  lv_obj_set_width(askBody_, 260);
  lv_label_set_text(askBody_, "");

  // Button row centred at y = 264 (chord = 322px). Two 130px buttons fit with
  // a 20px gap (130+20+130=280 ≤ 322). A third button is hidden by default.
  constexpr lv_coord_t kBtnY = 264;
  constexpr lv_coord_t kBtnW = 130;
  constexpr lv_coord_t kBtnH = 44;
  constexpr lv_coord_t kGap = 20;
  constexpr lv_coord_t kOffset = (kBtnW + kGap) / 2;  // 75

  // Allow button — left side
  askBtnAllow_ = lv_btn_create(askBg_);
  lv_obj_set_size(askBtnAllow_, kBtnW, kBtnH);
  lv_obj_align(askBtnAllow_, LV_ALIGN_CENTER, -kOffset, kBtnY - 180);
  lv_obj_set_style_radius(askBtnAllow_, 8, 0);
  lv_obj_set_style_bg_color(askBtnAllow_, kGreen, 0);
  lv_obj_add_event_cb(askBtnAllow_, DialUi::askButtonClicked, LV_EVENT_CLICKED,
                      reinterpret_cast<void*>(static_cast<uintptr_t>(0)));
  lv_obj_t* lblAllow = lv_label_create(askBtnAllow_);
  lv_obj_set_style_text_font(lblAllow, &dsh_font_cjk_16, 0);
  lv_label_set_text(lblAllow, "允许");
  lv_obj_center(lblAllow);

  // Deny button — right side
  askBtnDeny_ = lv_btn_create(askBg_);
  lv_obj_set_size(askBtnDeny_, kBtnW, kBtnH);
  lv_obj_align(askBtnDeny_, LV_ALIGN_CENTER, kOffset, kBtnY - 180);
  lv_obj_set_style_radius(askBtnDeny_, 8, 0);
  lv_obj_set_style_bg_color(askBtnDeny_, kRed, 0);
  lv_obj_add_event_cb(askBtnDeny_, DialUi::askButtonClicked, LV_EVENT_CLICKED,
                      reinterpret_cast<void*>(static_cast<uintptr_t>(1)));
  lv_obj_t* lblDeny = lv_label_create(askBtnDeny_);
  lv_obj_set_style_text_font(lblDeny, &dsh_font_cjk_16, 0);
  lv_label_set_text(lblDeny, "拒绝");
  lv_obj_center(lblDeny);

  // Third option — centred below the pair, for three-option asks.
  askBtnThird_ = lv_btn_create(askBg_);
  lv_obj_set_size(askBtnThird_, kBtnW, kBtnH);
  lv_obj_align(askBtnThird_, LV_ALIGN_CENTER, 0, kBtnY - 180 + kBtnH + 8);
  lv_obj_set_style_radius(askBtnThird_, 8, 0);
  lv_obj_set_style_bg_color(askBtnThird_, kGray, 0);
  lv_obj_add_event_cb(askBtnThird_, DialUi::askButtonClicked, LV_EVENT_CLICKED,
                      reinterpret_cast<void*>(static_cast<uintptr_t>(2)));
  lv_obj_t* lblThird = lv_label_create(askBtnThird_);
  lv_obj_set_style_text_font(lblThird, &dsh_font_cjk_16, 0);
  lv_label_set_text(lblThird, "");
  lv_obj_center(lblThird);
  lv_obj_add_flag(askBtnThird_, LV_OBJ_FLAG_HIDDEN);
}

// ── state update ─────────────────────────────────────────────────────────

void DialUi::setState(const JsonDocument& doc) {
  // The provisioning screen owns the display while it is up: a state frame
  // arriving mid-setup must not paint over the credentials the user is reading.
  if (provisioning_) return;

  const char* phaseStr = doc["phase"] | "";
  DialPhase newPhase = DialPhase::Idle;

  if (strcmp(phaseStr, "working") == 0) newPhase = DialPhase::Working;
  else if (strcmp(phaseStr, "thinking") == 0) newPhase = DialPhase::Thinking;
  else if (strcmp(phaseStr, "waiting") == 0) newPhase = DialPhase::Waiting;
  else if (strcmp(phaseStr, "done") == 0) newPhase = DialPhase::Done;
  else if (strcmp(phaseStr, "error") == 0) newPhase = DialPhase::Error;
  else if (strcmp(phaseStr, "idle") == 0) newPhase = DialPhase::Idle;
  else if (strcmp(phaseStr, "offline") == 0) newPhase = DialPhase::Offline;

  // If waiting, we have an ask overlay; the state update does not replace it.
  if (waiting_) return;

  phase_ = newPhase;

  // `done` is a transient that auto-dismisses; track its start.
  if (newPhase == DialPhase::Done) {
    doneShowMs_ = millis();
  } else {
    doneShowMs_ = 0;
  }

  // Update the arc for context pressure, then the labels and background colour.
  uint8_t ctx = doc["ctx"] | 0;
  updateArc(ctx);

  setPhaseLabel(newPhase);
  lv_obj_set_style_bg_color(statusBg_, colorForPhase(newPhase, stale_), 0);

  const char* title = doc["title"] | "";
  if (strlen(title) > 0) lv_label_set_text(titleLabel_, title);
  lv_label_set_text(detailLabel_, doc["detail"] | "");

  // Each phase owns a different centre: idle is a clock, working is the list of
  // what DSH is doing. Toggling visibility here keeps the two from overlapping.
  const bool idleFace = (newPhase == DialPhase::Idle ||
                         newPhase == DialPhase::Thinking ||
                         newPhase == DialPhase::Offline);
  if (idleFace) {
    // Show the clock and its subtitle.
    lv_obj_clear_flag(clockLabel_, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(clockSubLabel_, LV_OBJ_FLAG_HIDDEN);
    // Hide the working-phase detail label: it overlaps the idle grid's
    // bottom row, and its text (the last tool's command) is noise on idle.
    lv_obj_add_flag(detailLabel_, LV_OBJ_FLAG_HIDDEN);
    // Hide the working-phase activity list.
    for (uint8_t i = 0; i < kActivityLines; ++i) {
      lv_obj_add_flag(activityRows_[i], LV_OBJ_FLAG_HIDDEN);
    }
    // The old ticker is gone — three-column grid replaces it.
    for (int i = 0; i < 4; ++i) {
      lv_obj_clear_flag(idleColLeft_[i], LV_OBJ_FLAG_HIDDEN);
      lv_obj_clear_flag(idleColRight_[i], LV_OBJ_FLAG_HIDDEN);
      lv_obj_clear_flag(idleNameLeft_[i], LV_OBJ_FLAG_HIDDEN);
      lv_obj_clear_flag(idleNameRight_[i], LV_OBJ_FLAG_HIDDEN);
    }
  } else {
    lv_obj_add_flag(clockLabel_, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(clockSubLabel_, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(detailLabel_, LV_OBJ_FLAG_HIDDEN);
    for (int i = 0; i < 4; ++i) {
      lv_obj_add_flag(idleColLeft_[i], LV_OBJ_FLAG_HIDDEN);
      lv_obj_add_flag(idleColRight_[i], LV_OBJ_FLAG_HIDDEN);
      lv_obj_add_flag(idleNameLeft_[i], LV_OBJ_FLAG_HIDDEN);
      lv_obj_add_flag(idleNameRight_[i], LV_OBJ_FLAG_HIDDEN);
    }
  }

  // The clock face carries a one-line summary of the day beside the time.
  if (idleFace) {
    const char* clockText = doc["clock"] | "";
    if (strlen(clockText) > 0) lv_label_set_text(clockLabel_, clockText);
    const char* sub = doc["clockSub"] | "";
    lv_label_set_text(clockSubLabel_, strlen(sub) > 0 ? sub
                      : (newPhase == DialPhase::Offline ? "正在重连"
                        : newPhase == DialPhase::Thinking ? "思考中"
                                                          : "空闲中"));
  }

  // Populate the three-column stat rows from the structured `s` object.
  // Only value labels change — names are fixed at build time.
  if (idleFace) {
    const char* leftKeys[] = { "turns", "steps", "llm", "tool" };
    const char* rightKeys[] = { "ttft", "tps", "cache", "inp" };
    JsonObjectConst s = doc["s"].as<JsonObjectConst>();
    for (int i = 0; i < 4; ++i) {
      const char* v = s.isNull() ? "" : (s[leftKeys[i]] | "");
      lv_label_set_text(idleColLeft_[i], strlen(v) > 0 ? v : "-");
      const char* vr = s.isNull() ? "" : (s[rightKeys[i]] | "");
      lv_label_set_text(idleColRight_[i], strlen(vr) > 0 ? vr : "-");
    }
  }

  // Context pressure text under the clock, visible only while idle.
  if (idleFace && footerMid_ != nullptr) {
    const uint8_t ctx = doc["ctx"] | 0;
    if (ctx > 0) {
      char buf[24];
      snprintf(buf, sizeof(buf), "上下文 %u%%", ctx);
      lv_label_set_text(footerMid_, buf);
      lv_obj_set_style_text_color(footerMid_,
          ctx < 50 ? kGreen : ctx < 80 ? kYellow : kRed, 0);
      lv_obj_clear_flag(footerMid_, LV_OBJ_FLAG_HIDDEN);
    } else {
      lv_label_set_text(footerMid_, "");
      lv_obj_add_flag(footerMid_, LV_OBJ_FLAG_HIDDEN);
    }
  } else if (footerMid_ != nullptr) {
    lv_obj_add_flag(footerMid_, LV_OBJ_FLAG_HIDDEN);
  }

  setActivity(doc);
  setStats(doc);
  setFooter(doc);
}

/**
 * Fill the working-phase activity list from the state frame's `acts` array.
 *
 * The bridge sends the newest tool calls oldest-first; the running one is drawn
 * white and the finished ones grey, so the current step is findable without
 * reading every row. An absent `acts` array leaves the rows blank rather than
 * inventing content — a dial that guesses is worse than one that says nothing.
 */
void DialUi::setActivity(const JsonDocument& doc) {
  const bool working = (phase_ == DialPhase::Working ||
                        phase_ == DialPhase::Done ||
                        phase_ == DialPhase::Error);
  if (!working) return;

  JsonArrayConst acts = doc["acts"].as<JsonArrayConst>();
  uint8_t row = 0;
  for (JsonObjectConst act : acts) {
    if (row >= kActivityLines) break;
    const char* text = act["t"] | "";
    const bool running = act["r"] | false;
    lv_label_set_text(activityRows_[row], text);
    // The running row is the answer to "what is it doing right now", so it gets
    // full contrast while completed rows recede.
    lv_obj_set_style_text_color(activityRows_[row], running ? kWhite : kGray, 0);
    lv_obj_clear_flag(activityRows_[row], LV_OBJ_FLAG_HIDDEN);
    ++row;
  }
  // Any row the frame did not fill must be cleared, or a shorter list would
  // leave stale lines from the previous frame on screen.
  for (; row < kActivityLines; ++row) {
    lv_label_set_text(activityRows_[row], "");
    lv_obj_add_flag(activityRows_[row], LV_OBJ_FLAG_HIDDEN);
  }
}

/**
 * Show the session counters while idle.
 *
 * The bridge pre-formats this line because the numbers need unit conversion
 * (ms→minutes, tokens→millions) that belongs with the data, not on a device
 * whose job is to render. It scrolls because the full line is ~110 characters
 * against a circle that fits about 20.
 */
void DialUi::setStats(const JsonDocument& doc) {
  // The old scrolling ticker is gone — the three-column stat grid in
  // setState replaced it. This method remains for call-site compatibility.
  (void)doc;
}

/**
 * Draw the always-on footer: link state on the left, battery on the right.
 *
 * These two facts answer "is the dial still telling me the truth?", so they are
 * the one part of the screen no phase is allowed to take over. Both use LVGL
 * built-in symbols, which exist in every font build and cannot render as boxes.
 */
void DialUi::setFooter(const JsonDocument& doc) {
  if (footerIcon_ == nullptr || footerText_ == nullptr ||
      footerRight_ == nullptr) {
    return;
  }

  const bool linked = (phase_ != DialPhase::Offline);
  // Stale data is a third state: the link is up but the numbers are old, and
  // saying "connected" then would be a lie the user cannot detect.
  const char* icon = !linked ? LV_SYMBOL_CLOSE
                   : stale_  ? LV_SYMBOL_WARNING
                             : LV_SYMBOL_WIFI;
  const char* text = !linked ? "离线" : stale_ ? "陈旧" : "已连接";
  const lv_color_t colour = (linked && !stale_) ? kGreen : kGray;

  lv_label_set_text(footerIcon_, icon);
  lv_obj_set_style_text_color(footerIcon_, colour, 0);
  lv_label_set_text(footerText_, text);
  lv_obj_set_style_text_color(footerText_, colour, 0);

  const uint8_t battery = doc["battery"] | 0;
  if (battery > 0) {
    // ASCII only: the percent sign and digits exist in the CJK font, while a
    // battery symbol would not.
    char buf[16];
    snprintf(buf, sizeof(buf), "%u%%", battery);
    lv_label_set_text(footerRight_, buf);
    lv_obj_set_style_text_color(footerRight_, battery < 20 ? kRed : kGray, 0);
  } else {
    lv_label_set_text(footerRight_, "");
  }

  // footerMid_ is handled in setState as a clock-adjacent label.
}

void DialUi::updateArc(uint8_t ctxPercent) {
  if (arc_ == nullptr) return;
  // Animate the arc value from its current position to the new target, so the
  // ring looks alive rather than jumping. 300 ms ease-out makes the motion
  // visible without feeling sluggish — a status dial should not compete with
  // a busy indicator.
  //
  // The colour still sets instantly: interpolating hue would need an HSL exec
  // callback, and the arc's green/yellow/red bands are already a fast read.
  lv_anim_del(arc_, arcAnimCb_);
  lv_anim_init(&arcAnim_);
  lv_anim_set_var(&arcAnim_, arc_);
  lv_anim_set_exec_cb(&arcAnim_, arcAnimCb_);
  lv_anim_set_values(&arcAnim_, lv_arc_get_value(arc_), ctxPercent);
  lv_anim_set_time(&arcAnim_, 300);
  lv_anim_set_path_cb(&arcAnim_, lv_anim_path_ease_out);
  lv_anim_start(&arcAnim_);

  // The indicator colour tracks the pressure level: green → yellow → red.
  lv_color_t arcColor;
  if (ctxPercent < 50) arcColor = kGreen;
  else if (ctxPercent < 80) arcColor = kYellow;
  else arcColor = kRed;
  lv_obj_set_style_arc_color(arc_, arcColor, LV_PART_INDICATOR);
}

void DialUi::setPhaseLabel(DialPhase phase) {
  if (phaseLabel_ == nullptr) return;
  // LVGL's built-in symbols are part of every Montserrat build, so they always
  // render. Arbitrary Unicode glyphs (✓ ✕ ⌀ ⋯) are not in the font and would
  // come out as empty boxes — the whole point of the dial is being readable at
  // a glance, so the icon must never be a placeholder.
  const char* text;
  switch (phase) {
    case DialPhase::Idle:      text = LV_SYMBOL_MINUS;    break;  // resting
    case DialPhase::Working:   text = LV_SYMBOL_REFRESH;  break;  // busy
    case DialPhase::Thinking:  text = LV_SYMBOL_EYE_OPEN;  break;  // LLM thinking
    case DialPhase::Waiting:   text = LV_SYMBOL_WARNING;  break;  // needs you
    case DialPhase::Done:      text = LV_SYMBOL_OK;       break;
    case DialPhase::Error:     text = LV_SYMBOL_CLOSE;    break;
    case DialPhase::Offline:   text = LV_SYMBOL_EYE_CLOSE; break;  // link down
    default:                   text = LV_SYMBOL_MINUS;    break;
  }
  lv_label_set_text(phaseLabel_, text);
}

// ── ask overlay ──────────────────────────────────────────────────────────

void DialUi::showAsk(const JsonDocument& doc) {
  // While provisioning, there is no bridge link to answer over.
  if (provisioning_) return;

  waiting_ = true;
  phase_ = DialPhase::Waiting;

  // Copy the ask data into the active struct.
  const char* id = doc["id"] | "";
  strncpy(activeAsk_.id, id, sizeof(activeAsk_.id) - 1);
  activeAsk_.id[sizeof(activeAsk_.id) - 1] = '\0';

  const char* title = doc["title"] | "";
  strncpy(activeAsk_.title, title, sizeof(activeAsk_.title) - 1);
  activeAsk_.title[sizeof(activeAsk_.title) - 1] = '\0';

  const char* body = doc["body"] | "";
  strncpy(activeAsk_.body, body, sizeof(activeAsk_.body) - 1);
  activeAsk_.body[sizeof(activeAsk_.body) - 1] = '\0';

  activeAsk_.expiresAt = millis() + DSH_ASK_TIMEOUT_MS;
  activeAsk_.optionCount = 0;

  JsonArrayConst options = doc["options"].as<JsonArrayConst>();
  for (JsonObjectConst opt : options) {
    if (activeAsk_.optionCount >= 3) break;
    strncpy(activeAsk_.options[activeAsk_.optionCount].id, opt["id"] | "", 14);
    strncpy(activeAsk_.options[activeAsk_.optionCount].label, opt["label"] | "", 10);
    const char* style = opt["style"] | "";
    activeAsk_.options[activeAsk_.optionCount].primary = (strcmp(style, "primary") == 0);
    activeAsk_.optionCount++;
  }

  // Update the overlay UI.
  lv_label_set_text(askTitle_, title);
  lv_label_set_text(askBody_, body);

  // Show/hide buttons based on option count.
  if (activeAsk_.optionCount >= 1) {
    lv_obj_clear_flag(askBtnAllow_, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t* lbl = lv_obj_get_child(askBtnAllow_, 0);
    if (lbl) lv_label_set_text(lbl, activeAsk_.options[0].label);
    lv_obj_set_style_bg_color(askBtnAllow_,
        activeAsk_.options[0].primary ? kGreen : kRed, 0);
  } else {
    lv_obj_add_flag(askBtnAllow_, LV_OBJ_FLAG_HIDDEN);
  }
  if (activeAsk_.optionCount >= 2) {
    lv_obj_clear_flag(askBtnDeny_, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t* lbl = lv_obj_get_child(askBtnDeny_, 0);
    if (lbl) lv_label_set_text(lbl, activeAsk_.options[1].label);
    lv_obj_set_style_bg_color(askBtnDeny_,
        activeAsk_.options[1].primary ? kGreen : kRed, 0);
  } else {
    lv_obj_add_flag(askBtnDeny_, LV_OBJ_FLAG_HIDDEN);
  }
  if (activeAsk_.optionCount >= 3) {
    lv_obj_clear_flag(askBtnThird_, LV_OBJ_FLAG_HIDDEN);
    lv_obj_t* lbl = lv_obj_get_child(askBtnThird_, 0);
    if (lbl) lv_label_set_text(lbl, activeAsk_.options[2].label);
    lv_obj_set_style_bg_color(askBtnThird_,
        activeAsk_.options[2].primary ? kGreen : kRed, 0);
  } else {
    lv_obj_add_flag(askBtnThird_, LV_OBJ_FLAG_HIDDEN);
  }

  lv_obj_clear_flag(askBg_, LV_OBJ_FLAG_HIDDEN);
}

void DialUi::dismissAsk() {
  waiting_ = false;
  lv_obj_add_flag(askBg_, LV_OBJ_FLAG_HIDDEN);
  if (pendingAnswer_) {
    free(pendingAnswer_);
    pendingAnswer_ = nullptr;
  }
}

// ── touch dispatch ───────────────────────────────────────────────────────

/**
 * Record the chosen option so the main loop can ship it.
 *
 * The UI does not send: it owns the screen, and the network belongs to the
 * caller. Keeping the send out of the callback also keeps LVGL's event context
 * free of blocking socket writes.
 */
void DialUi::recordAnswer(const char* optionId) {
  if (pendingAnswer_ != nullptr) free(pendingAnswer_);
  pendingAnswer_ = strdup(optionId);
}

// ── LVGL event trampolines ───────────────────────────────────────────────
// LVGL fires plain C function pointers, so these static members forward into
// the single dial instance. The option index rides in the event's user data,
// which keeps one callback for however many buttons an ask may have.

void DialUi::askButtonClicked(lv_event_t* event) {
  const auto index = reinterpret_cast<uintptr_t>(lv_event_get_user_data(event));
  dialUi.onAskButton(static_cast<uint8_t>(index));
}

void DialUi::backgroundLongPressed(lv_event_t* /*event*/) {
  dialUi.onBackgroundLongPress();
}

/** Resolve a button index to its option id and record it. */
void DialUi::onAskButton(uint8_t index) {
  if (!waiting_ || index >= activeAsk_.optionCount) return;
  recordAnswer(activeAsk_.options[index].id);
}

/**
 * A long press on the dial background asks the main loop to reopen setup.
 *
 * The main loop owns the mode machine, so this only raises a flag; the loop
 * notices it on the next pass, drops the bridge link, and starts the portal.
 * Nothing here blocks, and nothing here touches the link the loop is using.
 */
void DialUi::onBackgroundLongPress() {
  if (provisioning_ || waiting_) return;  // already asking for attention
  reprovisionRequested_ = true;
}

// ── provisioning screen ──────────────────────────────────────────────────

void DialUi::buildProvisioningScreen() {
  provBg_ = lv_obj_create(lv_scr_act());
  lv_obj_set_size(provBg_, 360, 360);
  lv_obj_set_pos(provBg_, 0, 0);
  lv_obj_set_style_radius(provBg_, 180, 0);
  lv_obj_set_style_border_width(provBg_, 0, 0);
  lv_obj_set_style_bg_color(provBg_, kBlue, 0);
  lv_obj_set_style_bg_opa(provBg_, 255, 0);
  lv_obj_clear_flag(provBg_, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_add_flag(provBg_, LV_OBJ_FLAG_HIDDEN);

  // Reason for setup mode, at the top of the circle.
  provTitle_ = lv_label_create(provBg_);
  lv_obj_align(provTitle_, LV_ALIGN_TOP_MID, 0, 40);
  lv_obj_set_style_text_font(provTitle_, &dsh_font_cjk_16, 0);
  lv_obj_set_style_text_color(provTitle_, kWhite, 0);
  lv_obj_set_style_text_align(provTitle_, LV_TEXT_ALIGN_CENTER, 0);
  lv_label_set_long_mode(provTitle_, LV_LABEL_LONG_WRAP);
  lv_obj_set_width(provTitle_, 260);
  lv_label_set_text(provTitle_, "");

  // QR code, centred. A phone camera reads it and joins the AP with no typing.
  provQr_ = lv_qrcode_create(provBg_, 132, kDarkBg, kWhite);
  lv_obj_align(provQr_, LV_ALIGN_CENTER, 0, -8);

  // AP credentials, printed for the case where the camera cannot be used.
  provCreds_ = lv_label_create(provBg_);
  lv_obj_align(provCreds_, LV_ALIGN_BOTTOM_MID, 0, -56);
  lv_obj_set_style_text_font(provCreds_, &lv_font_montserrat_14, 0);
  lv_obj_set_style_text_color(provCreds_, kWhite, 0);
  lv_obj_set_style_text_align(provCreds_, LV_TEXT_ALIGN_CENTER, 0);
  lv_label_set_text(provCreds_, "");

  // Portal URL to open once joined.
  provUrl_ = lv_label_create(provBg_);
  lv_obj_align(provUrl_, LV_ALIGN_BOTTOM_MID, 0, -32);
  lv_obj_set_style_text_font(provUrl_, &lv_font_montserrat_14, 0);
  lv_obj_set_style_text_color(provUrl_, kYellow, 0);
  lv_label_set_text(provUrl_, "");
}

void DialUi::showProvisioning(const char* apSsid, const char* apPassword,
                              const char* portalUrl, const char* reason) {
  if (provBg_ == nullptr) return;
  provisioning_ = true;

  // The reason line doubles as the instruction: a user looking at this screen
  // for the first time needs to know what to do, not just what happened.
  char header[96];
  snprintf(header, sizeof(header), "%s\n手机扫码连接",
           reason != nullptr ? reason : "设备配置");
  lv_label_set_text(provTitle_, header);

  // A WIFI: URI makes the phone offer to join the network directly. WPA is
  // hard-coded because deriveCredentials always sets a password.
  char wifiUri[128];
  snprintf(wifiUri, sizeof(wifiUri), "WIFI:T:WPA;S:%s;P:%s;;",
           apSsid != nullptr ? apSsid : "", apPassword != nullptr ? apPassword : "");
  lv_qrcode_update(provQr_, wifiUri, strlen(wifiUri));

  // Printed credentials for the case where the camera cannot be used: the SSID
  // and password are ASCII, so Montserrat renders them fine.
  char creds[96];
  snprintf(creds, sizeof(creds), "%s / %s", apSsid != nullptr ? apSsid : "",
           apPassword != nullptr ? apPassword : "");
  lv_label_set_text(provCreds_, creds);

  lv_label_set_text(provUrl_, portalUrl != nullptr ? portalUrl : "");

  // The provisioning screen outranks both the dial and any stale ask.
  lv_obj_add_flag(askBg_, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(provBg_, LV_OBJ_FLAG_HIDDEN);
  lv_obj_move_foreground(provBg_);
}

void DialUi::hideProvisioning() {
  if (provBg_ == nullptr) return;
  provisioning_ = false;
  lv_obj_add_flag(provBg_, LV_OBJ_FLAG_HIDDEN);
}

// ── connection status ────────────────────────────────────────────────────

/**
 * Report link progress on the detail line while no state frame has arrived.
 *
 * Kept separate from setState so a connection message can never be mistaken for
 * session data: the phase stays Offline until the bridge actually speaks.
 *
 * Everything that belongs to a live session is hidden here rather than left at
 * its last value. During startup those widgets hold nothing meaningful, and
 * leaving the clock, activity rows and statistics ticker on screen alongside the
 * connection message is what made this screen feel crowded — seven elements
 * competing inside a 360px circle to say one thing: "connecting".
 */
void DialUi::setConnecting(const char* message) {
  if (provisioning_ || waiting_) return;
  phase_ = DialPhase::Offline;
  setPhaseLabel(DialPhase::Offline);
  lv_obj_set_style_bg_color(statusBg_, colorForPhase(DialPhase::Offline, false), 0);

  // The product name is the title; the progress message goes below it. Both are
  // centred, and nothing else is drawn.
  lv_label_set_text(titleLabel_, "DeepSeek Harness");
  lv_label_set_text(detailLabel_, message != nullptr ? message : "");

  // Hide the session widgets: they have no data yet.
  if (clockLabel_ != nullptr) lv_obj_add_flag(clockLabel_, LV_OBJ_FLAG_HIDDEN);
  if (clockSubLabel_ != nullptr) lv_obj_add_flag(clockSubLabel_, LV_OBJ_FLAG_HIDDEN);
  for (int i = 0; i < kActivityLines; ++i) {
    if (activityRows_[i] != nullptr) {
      lv_obj_add_flag(activityRows_[i], LV_OBJ_FLAG_HIDDEN);
    }
  }
  for (int i = 0; i < 4; ++i) {
    if (idleColLeft_[i] != nullptr) lv_obj_add_flag(idleColLeft_[i], LV_OBJ_FLAG_HIDDEN);
    if (idleColRight_[i] != nullptr) lv_obj_add_flag(idleColRight_[i], LV_OBJ_FLAG_HIDDEN);
    if (idleNameLeft_[i] != nullptr) lv_obj_add_flag(idleNameLeft_[i], LV_OBJ_FLAG_HIDDEN);
    if (idleNameRight_[i] != nullptr) lv_obj_add_flag(idleNameRight_[i], LV_OBJ_FLAG_HIDDEN);
  }
  // The footer stays: link state and battery are exactly what matters now.
  if (footerMid_ != nullptr) lv_obj_add_flag(footerMid_, LV_OBJ_FLAG_HIDDEN);
  updateArc(0);
}

// ── backlight ────────────────────────────────────────────────────────────

void DialUi::setBacklight(uint8_t level) {
  backlight_ = level;
  // Backlight control is handled outside this class via the LEDC API.
}

// ── main loop call ───────────────────────────────────────────────────────

void DialUi::loop() {
  lv_timer_handler();

  // Auto-dismiss the `done` phase after 4 s.
  if (doneShowMs_ > 0 && millis() - doneShowMs_ > 4000) {
    doneShowMs_ = 0;
    if (phase_ == DialPhase::Done) {
      phase_ = DialPhase::Idle;
      setPhaseLabel(DialPhase::Idle);
      lv_obj_set_style_bg_color(statusBg_, colorForPhase(DialPhase::Idle, stale_), 0);
    }
  }

  // Auto-dismiss the ask overlay on expiry.
  if (waiting_ && millis() > activeAsk_.expiresAt) {
    dismissAsk();
  }
}